function data_const = get_design_data_const()
% Get the inductor data which are common for all the sample (not only numeric, any data type).
%
%    Returns:
%        data_const (struct): inductor data common for all the sample
%
%    (c) 2019-2020, ETH Zurich, Power Electronic Systems Laboratory, T. Guillod

% data controlling the thermal/loss iteration:
%     - n_iter: maximum number of iterations
%     - losses.tol_abs: absolute tolerance on the losses
%     - losses.tol_rel: relative tolerance on the losses
%     - losses.relax: relaxation parameter for the losses
%     - thermal.tol_abs: absolute tolerance on the temperatures
%     - thermal.tol_rel: relative tolerance on the temperatures
%     - thermal.relax: relaxation parameter for the temperatures
data_const.iter.n_iter = 15;
data_const.iter.losses.tol_abs = 0.5;
data_const.iter.losses.tol_rel = 0.05;
data_const.iter.losses.relax = 1.0;
data_const.iter.thermal.tol_abs = 2.0;
data_const.iter.thermal.tol_rel = 0.05;
data_const.iter.thermal.relax = 1.0;

% data controlling the waveform generation:
%     - n_freq: number of harmonics for the Fourier series
%     - n_time: maximum number of iterations
data_const.signal.n_freq = 10;
data_const.signal.n_time = 20;

% data containing the material (core, winding, and insulation) data:
%    - each material has a unique id
%    - the material data is generated by 'resources/material'
data_const.material_core = load('source_input/material/core_data.mat');
data_const.material_winding = load('source_input/material/winding_data.mat');
data_const.material_iso = load('source_input/material/iso_data.mat');

end